### ISSUE TITLE
Problem with SPICE

### ISSUE THREAD

**Issue by rasoolfa** [peteanderson80/coco-caption#1]
Hi,

I was trying to report the SPICE for our paper; however, we faced multiple problems to make it work. I exactly followed the provided instructions to incorporate the spice into our evaluation procedure. 
Anyway, I got the following errors:

Error: Could not score batched file input:
org.fusesource.lmdbjni.LMDBException: MDB_CURSOR_FULL: Internal error - cursor stack limit reached
        at org.fusesource.lmdbjni.Util.checkErrorCode(Util.java:44)
        at org.fusesource.lmdbjni.Database.get(Database.java:202)
        at org.fusesource.lmdbjni.Database.get(Database.java:193)
        at org.fusesource.lmdbjni.Database.get(Database.java:186)
        at org.fusesource.lmdbjni.Database.get(Database.java:161)
        at edu.anu.spice.LmdbTupleDB.getTransaction(LmdbTupleDB.java:96)
        at edu.anu.spice.SpiceParser.loadTuplesFromDB(SpiceParser.java:195)
        at edu.anu.spice.SpiceParser.loadTuples(SpiceParser.java:245)
        at edu.anu.spice.SpiceParser.parseCaptions(SpiceParser.java:251)
        at edu.anu.spice.SpiceScorer.scoreBatch(SpiceScorer.java:109)
        at edu.anu.spice.SpiceScorer.main(SpiceScorer.java:60)
 
I was wondering have you ever faced with the problem like above? [This happens once a while] It is worth noting that our system works with MSCOCO evolution server with no problems.  I'd be appreciated if you please let me know your comment.

Rasool

**Comment by peteanderson80** [comment]
Hi,

I haven't seen this before. The problem is originating from the LMDB database that is used to cache parsed reference captions. This is purely for speeding up repeated evaluations, so you can disable it. To do this, just delete the line  `'-cache', cache_dir,` at /pycocoevalcap/spice/spice.py:64. Evaluations will be slower but it will definitely avoid this error.

To fix the problem, I had a quick look at the LMDB docs, but there is no further information about this error or how to resolve it. I'm not an LMDB expert so it might take a bit of digging around in the LMDB code to understand the cause.

**Comment by rasoolfa** [comment]
Hi
Thanks for your response.
Yes, it caused by cache. I did a similar thing but in a different way as you mentioned that to delete the cache after every single run. With this trick, it works. But I guess deleting that line would be a better way to deal with this. Thanks again.

**Comment by AtharvTalnikar** [comment]
Hi!
I am having issues implementing SPICE.Please help

Error: Could not score batched file input:
java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to java.lang.String
	at edu.anu.spice.SpiceScorer.scoreBatch(SpiceScorer.java:95)
	at edu.anu.spice.SpiceScorer.main(SpiceScorer.java:60)
Traceback (most recent call last):
  File "/content/pycocoevalcap/spice/model_evaluation.py", line 238, in <module>
    Val_with_MLE()
  File "/content/pycocoevalcap/spice/model_evaluation.py", line 236, in Val_with_MLE
    spice_class.compute_score(all_usable_ref,all_gen_sents)
  File "/content/pycocoevalcap/spice/test.py", line 78, in compute_score
    cwd=os.path.dirname(os.path.abspath(__file__)))
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', '-Xmx8G', 'spice-1.0.jar', '/content/pycocoevalcap/spice/tmp/tmpr49ny2ll', '-cache', '/content/pycocoevalcap/spice/cache', '-out', '/content/pycocoevalcap/spice/tmp/tmpl8edcdti', '-subset', '-silent']' returned non-zero exit status 1.

**Comment by Robertwyq** [comment]
I meet this problem too, how do you fix it

**Comment by HN123-123** [comment]
> Hi!
> I am having issues implementing SPICE.Please help
> 
> Error: Could not score batched file input:
> java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to java.lang.String
> at edu.anu.spice.SpiceScorer.scoreBatch(SpiceScorer.java:95)
> at edu.anu.spice.SpiceScorer.main(SpiceScorer.java:60)
> Traceback (most recent call last):
> File "/content/pycocoevalcap/spice/model_evaluation.py", line 238, in
> Val_with_MLE()
> File "/content/pycocoevalcap/spice/model_evaluation.py", line 236, in Val_with_MLE
> spice_class.compute_score(all_usable_ref,all_gen_sents)
> File "/content/pycocoevalcap/spice/test.py", line 78, in compute_score
> cwd=os.path.dirname(os.path.abspath(**file**)))
> File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
> raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['java', '-jar', '-Xmx8G', 'spice-1.0.jar', '/content/pycocoevalcap/spice/tmp/tmpr49ny2ll', '-cache', '/content/pycocoevalcap/spice/cache', '-out', '/content/pycocoevalcap/spice/tmp/tmpl8edcdti', '-subset', '-silent']' returned non-zero exit status 1.

**Comment by WangLanxiao** [comment]
I meet this problem too, how do you fix it

**Comment by HenryHZY** [comment]
I have also met this problem "Error: Could not score batched file input". I cannot fix it apart from re-installing the whole environment. That is really confused.
