### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by wgharbieh** [peteanderson80/coco-caption#2]
Hi,
Thank you very much for the evaluation script. For my applications, I needed a Python 3.5 version of this script so I converted this code to be compatible with Python 3.5 and was wondering whether I can create a pull request to include it either in this repo or somewhere else.

Thanks again

**Comment by peteanderson80** [comment]
Thanks, it sounds like a good idea to have a Python 3.5 version. Rather than doing it here, I will try to merge this fork containing SPICE back into the [official repo](https://github.com/tylin/coco-caption) (to minimize duplicated effort).

**Comment by wgharbieh** [comment]
I agree, I opened the same issue there first but did not get any reply yet.
